I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/screens.rpy", line 1315, in script
    
  File "game/screens.rpy", line 1346, in <module>
    
  File "game/screens.rpy", line 1317, in fx
    def fx():
NameError: global name 'p_soutien' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/screens.rpy", line 1315, in script
    
  File "D:\Renpy\renpy-7.2.2-sdk\renpy\ast.py", line 900, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Renpy\renpy-7.2.2-sdk\renpy\python.py", line 1930, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/screens.rpy", line 1346, in <module>
    
  File "game/screens.rpy", line 1317, in fx
    def fx():
NameError: global name 'p_soutien' is not defined

Windows-8-6.2.9200
Ren'Py 7.2.2.491
 
Fri Jun 21 10:36:31 2019
